#
# Travis CI configuration
#

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.9-dev"
    - python: "nightly"

install:
  - pip install -qU pip pytest pytest-cov python-coveralls pytest-asyncio mock
  - pip install -q 'coverage<5.0'

script:
  - python setup.py pytest --addopts '--cov=growler --cov-report=term-missing'

after_success:
  - coveralls
